spring.application.name=sfrigola-core

server.servlet.context-path=/sfrigola-core
server.port=${SERVER_PORT}

# ===== Docker Compose =====
spring.docker.compose.file=docker-compose.yaml

# ===== PostgreSQL =====
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never

# ===== JPA / Hibernate =====
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===== Aspects =====
sc.aspect.execution-time.fast-threshold-ms=100
sc.aspect.execution-time.slow-threshold-ms=500